app/urls.py
# -*- encoding: utf-8 -*-

from django.urls import path, re_path
from app import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),
    path('mestransactions/', views.mestransactions, name='mestransactions'),
    path('transaction/', views.transaction, name='transaction'),
    path('profil/', views.profil, name='profil'),
    path('coin/<str:id_coin>/', views.coinView, name='coinView'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Coin(models.Model):
    id_user = models.IntegerField()
    id_coin = models.CharField(max_length=25)
    nom = models.CharField(db_column='Nom', max_length=25)  # Field name made lowercase.
    depenses = models.FloatField(db_column='Depenses')  # Field name made lowercase.
    total = models.FloatField(db_column='Total')  # Field name made lowercase.
    etat = models.FloatField(db_column='Etat', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Coin'


class Transaction(models.Model):
    id_user = models.IntegerField(blank=True, null=True)
    id_coin = models.ForeignKey(Coin, models.DO_NOTHING, db_column='id_coin')
    nom = models.CharField(db_column='Nom', max_length=25, blank=True, null=True)  # Field name made lowercase.
    total = models.FloatField(db_column='Total', blank=True, null=True)  # Field name made lowercase.
    prix_coin = models.FloatField(db_column='Prix_Coin', blank=True, null=True)  # Field name made lowercase.
    quantite = models.FloatField(db_column='Quantite', blank=True, null=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    frais = models.FloatField(db_column='Frais', blank=True, null=True)  # Field name made lowercase.
    etat = models.CharField(db_column='Etat', max_length=15)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Transaction'

core/templates/coin.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
              <div class="card-header card-header-warning card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">content_copy</i>
                </div>
                <p class="card-category">Prix du coin</p>
                <h3 class="card-title">{{ infos_coin.prix}}
                  <small>€</small>
                </h3>
              </div>
              <div class="card-footer">
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
              <div class="card-header card-header-warning card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">content_copy</i>
                </div>
                <p class="card-category">Etat</p>
                <h3 class="card-title">{{ coin.etat}} %</h3>
              </div>
              <div class="card-footer">
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
              <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">store</i>
                </div>
                <p class="card-category">Total</p>
                <h3 class="card-title">{{ infos_coin.total}} €</h3>
              </div>
              <div class="card-footer">
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Mes Transactions</h4>
                <p class="card-category">{{ nom }}</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                      <th>Prix du coin</th>
                      <th>Quantité</th>
                      <th>Total</th>
                      <th>Date</th>
                      <th>Fraix</th>
                      <th>Etat</th>
                    </thead>
                    <tbody>
                      {% for t in transaction %}
                      <tr>
                        <td>{{t.prix_coin}} €</td>
                        <td>{{t.quantite}}</td>
                        <td>{{t.total}} €</td>
                        <td>{{t.date}}</td>
                        <td>{{t.frais}} €</td>
                        <td>{{t.etat}}</td>
                        <td class="td-actions text-right">
                          <button type="button" rel="tooltip" title="Supprimer" class="btn btn-danger btn-link btn-sm">
                            <i class="material-icons">close</i>
                          </button>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">content_copy</i>
            </div>
            <p class="card-category">Solde du portefeuille</p>
            <h3 class="card-title">{{ portefeuille.solde }}
              <small>€</small>
            </h3>
          </div>
          <div class="card-footer">
            <!-- <div class="stats">
              <i class="material-icons text-danger">warning</i>
              <a href="#pablo">Get More Space...</a>
            </div> -->
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">store</i>
            </div>
            <p class="card-category">Dépenses totales</p>
            <h3 class="card-title">{{ portefeuille.depenses }} €</h3>
          </div>
          <div class="card-footer">
            <!-- <div class="stats">
              <i class="material-icons">date_range</i> Last 24 Hours
            </div> -->
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons">info_outline</i>
            </div>
            <p class="card-category">Frais</p>
            <h3 class="card-title">{{ portefeuille.frais }} €</h3>
          </div>
          <div class="card-footer">
            <!-- <div class="stats">
              <i class="material-icons">local_offer</i> Tracked from Github
            </div> -->
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Top Coin</h4>
            <p class="card-category">Cryptomonnaies les plus rentables</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <th>Nom</th>
                <th>Dépenses</th>
                <th>Total</th>
                <th>Etat</th>
              </thead>
              <tbody>
                {% for c in top_coin %}
                <tr>
                  <td><a href="/coin/{{c.id_coin}}/">{{c.nom}}</a></td>
                  <td>{{c.depenses}} €</td>
                  <td>{{c.total}} €</td>
                  <td>{{c.etat}} %</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

core/templates/mestransactions.html
{% extends "layouts/base.html" %}

{% block title %} UI Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Mes Transactions</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>Nom</th>
                        <th>Total</th>
                        <th>Quantité</th>
                        <th>Prix Du Coin</th>
                        <th>Date</th>
                        <th>Fraix</th>
                        <th>Etat</th>
                      </thead>
                      <tbody>
                        {% for t in transaction %}
                        <tr>
                          <td><a href="/coin/{{t.id_coin.id_coin}}/">{{t.nom}}</a></td>
                          <td>{{t.total}} €</td>
                          <td>{{t.quantite}}</td>
                          <td>{{t.prix_coin}} €</td>
                          <td>{{t.date}}</td>
                          <td>{{t.frais}} €</td>
                          <td>{{t.etat}}</td>
                          <td class="td-actions text-right">
                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-primary btn-link btn-sm">
                              <i class="material-icons">edit</i>
                            </button>
                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-link btn-sm">
                              <i class="material-icons">close</i>
                            </button>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-403.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 403</h6>
                    <h4 class="card-title">
                        Access Denied
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/profil.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Modifier Mon Profil</h4>
                  <p class="card-category">Compléter mes informations</p>
                </div>
                <div class="card-body">
                  <form>
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">UserID (disabled)</label>
                          <input type="text" class="form-control" disabled value="{{ request.user.id }}">
                        </div>
                      </div>
                      <div class="col-md-3">
                        <div class="form-group">
                          <label class="bmd-label-floating">Username</label>
                          <input type="text" class="form-control" value="{{ request.user.username }}">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Mail</label>
                          <input type="email" class="form-control" value="{{ request.user.email }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Prénom</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Nom</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Adresse</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Ville</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Pays</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Code Postal</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>About Me</label>
                          <div class="form-group">
                            <label class="bmd-label-floating"> Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</label>
                            <textarea class="form-control" rows="5"></textarea>
                          </div>
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Update Profile</button>
                    <div class="clearfix"></div>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card card-profile">
                <div class="card-avatar">
                  <a href="#pablo">
                    <img class="img" src="/static/assets/img/faces/marc.jpg" />
                  </a>
                </div>
                <div class="card-body">
                  <h6 class="card-category text-gray">
                    {{ request.user.username }}
                  </h6>
                  <h4 class="card-title">
                    {{ request.suser.email }}
                  </h4>
                  <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                  </p>
                  <a href="#pablo" class="btn btn-primary btn-round">Follow</a>
                </div>
              </div>
            </div>
          </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/transaction.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title">Ajouter Une Nouvelle Transaction</h4>
        </div>
        <div class="card-body">
            <h6 class="card-category">
                {% if msg %}
                    <span class="text-danger">{{ msg | safe }}</span>
                {% endif %}  
            </h6>
            
            <br />
            <form method="post" action="">
            {% csrf_token %} 
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                    <label class="bmd-label-floating">Nom</label>
                    {{ form.nom }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="bmd-label-floating">Prix par coin</label>
                        {{ form.prix_coin }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="bmd-label-floating">Quantité</label>
                        {{ form.quantite }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="bmd-label-floating">Total</label>
                        {{ form.total }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="bmd-label-floating">Frais</label>
                        {{ form.frais }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="bmd-label-floating">Date</label>
                        {{ form.date }}
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary pull-right">Ajouter</button>
            <div class="clearfix"></div>
            </form>
        </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>

    $('#id_nom').selectize({
      sortField: 'text'
    });

</script>
{% endblock javascripts %}

core/templates/ui-icons.html
{% extends "layouts/base.html" %}

{% block title %} UI Icons {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="container-fluid">
            <div class="card card-plain">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Material Design Icons</h4>
                <p class="card-category">Handcrafted by our friends from
                  <a target="_blank" href="https://design.google.com/icons/">Google</a>
                </p>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="card-body">
                    <div class="iframe-container d-none d-lg-block">
                      <iframe src="https://design.google.com/icons/">
                        <p>Your browser does not support iframes.</p>
                      </iframe>
                    </div>
                    <div class="col-md-12 d-none d-sm-block d-md-block d-lg-none d-block d-sm-none text-center ml-auto mr-auto">
                      <h5>The icons are visible on Desktop mode inside an iframe. Since the iframe is not working on Mobile and Tablets please visit the icons on their original page on Google. Check the
                        <a href="https://design.google.com/icons/" target="_blank">Material Icons</a>
                      </h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/ui-maps.html
{% extends "layouts/base.html" %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div id="map"></div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
  
{% endblock javascripts %}

core/templates/ui-typography.html
{% extends "layouts/base.html" %}

{% block title %} UI Typography {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Material Dashboard Heading</h4>
              <p class="card-category">Created using Roboto Font Family</p>
            </div>
            <div class="card-body">
              <div id="typography">
                <div class="card-title">
                  <h2>Typography</h2>
                </div>
                <div class="row">
                  <div class="tim-typo">
                    <h1>
                      <span class="tim-note">Header 1</span>The Life of Material Dashboard </h1>
                  </div>
                  <div class="tim-typo">
                    <h2>
                      <span class="tim-note">Header 2</span>The Life of Material Dashboard</h2>
                  </div>
                  <div class="tim-typo">
                    <h3>
                      <span class="tim-note">Header 3</span>The Life of Material Dashboard</h3>
                  </div>
                  <div class="tim-typo">
                    <h4>
                      <span class="tim-note">Header 4</span>The Life of Material Dashboard</h4>
                  </div>
                  <div class="tim-typo">
                    <h5>
                      <span class="tim-note">Header 5</span>The Life of Material Dashboard</h5>
                  </div>
                  <div class="tim-typo">
                    <h6>
                      <span class="tim-note">Header 6</span>The Life of Material Dashboard</h6>
                  </div>
                  <div class="tim-typo">
                    <p>
                      <span class="tim-note">Paragraph</span>
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.</p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Quote</span>
                    <blockquote class="blockquote">
                      <p>
                        I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.
                      </p>
                      <small>
                        Kanye West, Musician
                      </small>
                    </blockquote>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Muted Text</span>
                    <p class="text-muted">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
                    </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Primary Text</span>
                    <p class="text-primary">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Info Text</span>
                    <p class="text-info">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Success Text</span>
                    <p class="text-success">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Warning Text</span>
                    <p class="text-warning">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...
                    </p>
                  </div>
                  <div class="tim-typo">
                    <span class="tim-note">Danger Text</span>
                    <p class="text-danger">
                      I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>
                  </div>
                  <div class="tim-typo">
                    <h2>
                      <span class="tim-note">Small Tag</span>
                      Header with small subtitle
                      <br>
                      <small>Use "small" tag for the headers</small>
                    </h2>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}